version: '3.9'
services:
  # db:
  #   image: postgres:11.1-alpine
  #   volumes:
  #     - postgresql:/var/lib/postgresql/data
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 7001:7000
    env_file:
      - .env
    networks:
      - ollama_default
    # depends_on:
    #   - db
# volumes:
#   postgresql:
networks:
  ollama_default:
    external: true
