version: '3.9'
services:
  # db:
  #   image: postgres:11.1-alpine
  #   volumes:
  #     - postgresql:/var/lib/postgresql/data
  app:
    build: .
    command: pipenv run app
    volumes:
      - .:/app:cached
    ports:
      - 7001:7000
    env_file:
      - .env
    # depends_on:
    #   - db
# volumes:
#   postgresql:
